### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by jlag34** [CasOlckers/Capstone#2]
Your media queries look good but you’re missing your 3rd layout type. When I squish the page down to about 550-750px everything is really messed up. Many elements break their containers or overlap. The large and small views look good.

**Comment by CasOlckers** [comment]
Thanks. I misinterpreted the spec sheet only to have a mobile and PC view. I will attend to this soon

**Comment by CasOlckers** [comment]
Hi. I have added media queries to accommodate screen sizes between 481px and 768px.
