### ISSUE TITLE
Visuals

### ISSUE THREAD

**Issue by jlag34** [CasOlckers/Capstone#3]
Your project looks good on the largest view. Your layout is good and everything is where it’s suppose to be. I wish you had done a little more with the color scheme. The page is almost unusable at a medium width. I like that you got that nav bar icons to collapse. At the smallest width there are some things that need to be touched up (some things are off centered).

**Comment by CasOlckers** [comment]
Thanks for the feedback. I followed the spec sheet assumed only a mobile view and desktop virw was required. I will apply the middle view soon and will resend this to you for review.

**Comment by CasOlckers** [comment]
Hi. I have added media queries to accommodate medium sized screens. Looks better.
