### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by jlag34** [CasOlckers/Capstone#4]
Your project was on the edge between meets expectations and needs improvement. However, because you demonstrated you understand media queries I went with meets expectations. Your project is missing an entire screen size of media queries. Also, there are a few things style wise that need to be cleaned up. You did a good job on the media queries that were finished and using a variety of styles for the rest.

**Comment by CasOlckers** [comment]
Great news. I will close out the outstanding issues. Thanks for the feedback

**Comment by CasOlckers** [comment]
Hi. I have attended to the verification comments and added code to also accommodate medium sized screens.
